spring.application.name=pmt_api

server.port=8082

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/pmt_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris
spring.datasource.username=ron_malvaux
spring.datasource.password=pmt_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.web.error.include-stacktrace=never

pmt.jwt.secret=${PMT_JWT_SECRET:jewgrfjhgejqas svfbkqe  2fhbrqvahkew    fgvqejHHJRV Wb hfwgr    ju3w}
pmt.jwt.expiration-seconds=3600

pmt.cors.origins=${PMT_CORS_ORIGINS:http://localhost:4200}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
